var a = 100;
var b = 50;
var str1 = 'Hello';
var str2 = 'World';
var bool = true;
var  status = true;
var arr = [1,2,3,4,5,6,7];
var obj =  {"x":10,"y":20,"z":-20};
console.log('this is th forth object\nof the array with the index 3 ' + arr[3] + '\n');
console.log('This is x of obj -->' + obj.x);
console.log('\n');
console.log('This is just one quote \'');
console.log('This is just one tab \t >>>');
console.log('This is just one new line on Mac \n >>>');
console.log('This is just one new line on Win \r >>>');
console.log(a / (b - 1));
console.log(a * (b - 1));
console.log(a / (b + 1));
console.log('"' + str1 + ' ' + str2 + '"');
